[package]
name = "counting-contract"
version = "0.1.0"
edition = "2021"
 
[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
cosmwasm-std = "1.5.0"
serde = { version = "1.0.192", features = ["derive"] }

[dev-dependencies]
cw-multi-test = "0.18.0"
